# Site settings
title: "Matteo Mandrile CV"
description: "Matteo Mandrile's Curriculum Vitae"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Matteo Mandrile"
resume_title:                   "Architect | BIM & VDC Consultant | LEED Green Associate"
resume_contact_email:           "matteomandrile1@gmail.com"
resume_contact_telephone:       "(+39)3467060895"
resume_contact_address:         "Turin, Italy"
resume_header_contact_info: "Turin, Italy | (+39)3467060895 | matteomandrile1@gmail.com"
resume_header_intro: "<p>Academic background in Architecture and Sustainable Design, I studied at MIT, Polytechnic of Turin and University of Brasília. Specialization in BIM at the European Master in Building Information Modelling.

In recent years, I joined architectural and engineering firms in Italy, USA, and Brazil, to implement sustainable design strategies and BIM workflows.
My interests lie in the development and implementation of digital technologies and workflows to support sustainable design and construction processes, exploiting the latest innovation in digital technologies.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
#resume_section_associations:    true
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/matteomandrile"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/matteo-mandrile/"
  resume_leed_url:          "https://www.usgbc.org/people/matteo-mandrile/0011372159"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
